### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by hundanLi** [zh-plus/video-to-pose3D#24]
when I try to specify the architecture, it occurs such error:
`videopose.py: error: unrecognized arguments: -arc 3,3,3`.
How to address it, please?

**Comment by zh-plus** [comment]
The code is highly customized only for a convenient video processing job. Thus, you're not supposed to specify the architecture directly in the command. The architecture argument will not take effect because it's hard-coded [here](https://github.com/zh-plus/video-to-pose3D/blob/0f228014417bc66c18548f11c71f8ae7a4605a30/videopose.py#L81): `filter_widths=[3, 3, 3, 3, 3]`.

If you want to change the architecture, you can directly change the `filter_widths`.

**Comment by hundanLi** [comment]
Yes, I have manually change the `filter_widths`,  it works. But still wanna make it easier to change architecture, how to do that?

**Comment by zh-plus** [comment]
You can refer to the [facebook original script](https://github.com/zh-plus/video-to-pose3D/blob/0f228014417bc66c18548f11c71f8ae7a4605a30/origin_run.py) and check how to utilize `args.architerture`.

**Comment by hundanLi** [comment]
I found it can parse arguments, but occurs error when it run to this [line](https://github.com/zh-plus/video-to-pose3D/blob/0f228014417bc66c18548f11c71f8ae7a4605a30/videopose.py#L36).
